const data = [
  {
    id: 1,
    name: "Thao",
    age: "24",
    type: "GOOD",
    balance: 6867,
    subjects: ["math", "physic", "chemistry"],
  },
  {
    id: 2,
    name: "Lan",
    age: "26",
    type: "AVERAGE",
    balance: 14063,
    subjects: ["math", "physic", "art"],
  },
  {
    id: 3,
    name: "Duc",
    age: "23",
    type: "AVERAGE",
    balance: 18274,
    subjects: ["math", "art", "chemistry"],
  },
  {
    id: 4,
    name: "Thanh",
    age: "29",
    type: "GOOD",
    balance: 7189,
    subjects: ["art", "physic", "chemistry"],
  },
  {
    id: 5,
    name: "Thao",
    age: "30",
    type: "AVERAGE",
    balance: 7945,
    subjects: ["math", "English", "chemistry"],
  },
  {
    id: 6,
    name: "Quang",
    age: "24",
    type: "WEEK",
    balance: 11832,
    subjects: ["math", "English", "art"],
  },
  {
    id: 7,
    name: "Huyen",
    age: "27",
    type: "AVERAGE",
    balance: 18044,
    subjects: ["art", "physic", "chemistry"],
  },
  {
    id: 8,
    name: "Thao",
    age: "29",
    type: "WEEK",
    balance: 17338,
    subjects: ["math", "art", "English"],
  },
  {
    id: 9,
    name: "Manh",
    age: "28",
    type: "GOOD",
    balance: 7743,
    subjects: ["math", "physic", "chemistry"],
  },
  {
    id: 10,
    name: "Hai",
    age: "25",
    type: "AVERAGE",
    balance: 12676,
    subjects: ["English", "physic", "chemistry"],
  },
  {
    id: 11,
    name: "Hai",
    age: "30",
    type: "GOOD",
    balance: 17991,
    subjects: ["math", "physic", "chemistry"],
  },
  {
    id: 12,
    name: "Thanh",
    age: "27",
    type: "AVERAGE",
    balance: 9514,
    subjects: ["English", "art", "chemistry"],
  },
  {
    id: 13,
    name: "Thang",
    age: "30",
    type: "GOOD",
    balance: 5394,
    subjects: ["math", "art", "chemistry"],
  },
  {
    id: 14,
    name: "An",
    age: "26",
    type: "AVERAGE",
    balance: 10363,
    subjects: ["math", "physic", "chemistry"],
  },
  {
    id: 15,
    name: "An",
    age: "23",
    type: "AVERAGE",
    balance: 6210,
    subjects: ["math", "physic", "chemistry"],
  },
  {
    id: 16,
    name: "Hai",
    age: "29",
    type: "WEEK",
    balance: 8837,
    subjects: ["math", "physic", "English"],
  },
  {
    id: 17,
    name: "Thao",
    age: "29",
    type: "AVERAGE",
    balance: 6404,
    subjects: ["English", "physic", "art"],
  },
  {
    id: 18,
    name: "Huyen",
    age: "28",
    type: "GOOD",
    balance: 5175,
    subjects: ["math", "physic", "chemistry"],
  },
  {
    id: 19,
    name: "Huyen",
    age: "25",
    type: "GOOD",
    balance: 5163,
    subjects: ["art", "physic", "English"],
  },
  {
    id: 20,
    name: "Hai",
    age: "26",
    type: "AVERAGE",
    balance: 17285,
    subjects: ["English", "physic", "chemistry"],
  },
];

export default data;
